import { readFile } from "node:fs/promises";
import { describe, expect, test } from "vitest";

describe("Hardware acceptance readiness script contract", () => {
  test("provides a read-only readiness command before real target acceptance", async () => {
    const packageJson = JSON.parse(await readFile("package.json", "utf8")) as { scripts: Record<string, string> };

    expect(packageJson.scripts["acceptance:ready"]).toBe("npm run build --silent && tsx scripts/ccs-acceptance-readiness.ts");
  });

  test("checks MCP contracts and hardware preflight without target control", async () => {
    const source = await readFile("scripts/ccs-acceptance-readiness.ts", "utf8");

    expect(source).toContain("StdioClientTransport");
    expect(source).toContain('name: "c2000_getAcceptanceReadiness"');
    expect(source).not.toContain('from "../src/hardware/programDiscovery.js"');
    expect(source).not.toContain('from "../src/hardware/preflight.js"');
    expect(source).not.toContain('from "node:fs/promises"');
    expect(source).toContain("programDiscovery");
    expect(source).toContain("C2000_PROGRAM_SEARCH_ROOTS");
    expect(source).toContain("C2000_ALLOW_EXISTING_DEBUG_PROCESSES");
    expect(source).toContain("allowExistingDebugProcesses");
    expect(source).toContain("workspace_ccstheia");
    expect(source).toContain('name: "c2000_getToolContracts"');
    expect(source).not.toContain('name: "c2000_getDebugBoundary"');
    expect(source).not.toContain('name: "c2000_getHardwarePreflight"');
    expect(source).not.toContain('name: "c2000_discoverAcceptancePrograms"');
    expect(source).toContain("debugProcessDetails");
    expect(source).toContain("const debugProcessDetails = readiness.preflight?.debugProcessDetails");
    expect(source).not.toContain("Array.isArray(readiness.preflight?.debugProcessDetails)");
    expect(source).not.toContain("formatDebugProcessOwners");
    expect(source).toContain('"c2000_getDebugBoundary", "host", "host-read", []');
    expect(source).toContain('"c2000_getAcceptanceEvidence", "host", "host-read", []');
    expect(source).toContain('"c2000_discoverAcceptancePrograms", "host", "host-read", []');
    expect(source).toContain('"c2000_getAcceptanceReadiness", "host", "host-read", []');
    expect(source).toContain("officialTiMcpDebugControlsUsed");
    expect(source).toContain("activeTargetAllowed");
    expect(source).toContain("uiIndependenceEvidence");
    expect(source).toContain("readiness.uiIndependenceEvidence");
    expect(source).toContain("acceptanceEvidence");
    expect(source).toContain("readiness.acceptanceEvidence");
    expect(source).toContain("assertAcceptanceEvidence(acceptanceEvidence)");
    expect(source).toContain('"debug_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain('expectedCoreDebugTools: ["c2000_connectTarget", "c2000_disconnectTarget", "c2000_runCore", "c2000_continue", "c2000_haltCore", "c2000_pause", "c2000_reset", "c2000_getTargetState", "c2000_loadProgram"]');
    expect(source).toContain('expectedRequiredInputs: ["sessionId", "coreId"]');
    expect(source).toContain('expectedResponseCoreIdentityFields: ["coreId", "coreName"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreDebugTools, expected.expectedCoreDebugTools)");
    expect(source).toContain("assert.deepEqual(requirement.expectedRequiredInputs, expected.expectedRequiredInputs)");
    expect(source).toContain("assert.deepEqual(requirement.expectedResponseCoreIdentityFields, expected.expectedResponseCoreIdentityFields)");
    expect(source).toContain('"multicore_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedMulticoreToolContracts");
    expect(source).toContain('name: "c2000_loadPrograms"');
    expect(source).toContain('coreIdentityFields: ["programs[].coreId"]');
    expect(source).toContain('name: "c2000_getMulticoreSnapshot"');
    expect(source).toContain('responseCoreIdentityFields: ["cores[].coreId", "cores[].coreName"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedMulticoreToolContracts, expected.expectedMulticoreToolContracts)");
    expect(source).toContain('"core_read_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedCoreReadToolContracts");
    expect(source).toContain('name: "c2000_evaluateMany"');
    expect(source).toContain('requiredInputFields: ["sessionId", "coreId", "expressions"]');
    expect(source).toContain('name: "c2000_getLoadedProgramInfo"');
    expect(source).toContain('name: "c2000_resolvePc"');
    expect(source).toContain('name: "c2000_resolveAddress"');
    expect(source).toContain('requiredInputFields: ["sessionId", "coreId", "address"]');
    expect(source).toContain('name: "c2000_waitUntilExpression"');
    expect(source).toContain('requiredInputFields: ["sessionId", "coreId", "expression", "expected", "timeoutMs"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreReadToolContracts, expected.expectedCoreReadToolContracts)");
    expect(source).toContain('"advanced_automation_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedAdvancedAutomationToolContracts");
    expect(source).toContain('name: "c2000_assignExpressions"');
    expect(source).toContain('targetEffect: "memory-write"');
    expect(source).toContain('coreIdentityFields: ["assignments[].coreId"]');
    expect(source).toContain('name: "c2000_compareExpressions"');
    expect(source).toContain('coreIdentityFields: ["comparisons[].left.coreId", "comparisons[].right.coreId"]');
    expect(source).toContain('name: "c2000_diagnoseCpu2Boot"');
    expect(source).toContain('responseCoreIdentityFields: ["cpu1.coreId", "cpu2.coreId", "snapshot.cores[].coreId"]');
    expect(source).toContain('name: "c2000_launchMulticoreDebug"');
    expect(source).toContain('"c2000_runIpcAcceptance", "launch", "launch-workflow", ["sessionId", "cpu1CoreId", "cpu2CoreId", "cpu1OutPath", "cpu2OutPath", "cpu1MapPath", "cpu2MapPath", "timeoutMs"]');
    expect(source).toContain('"c2000_runBootHandoffDiagnosis", "launch", "launch-workflow", ["sessionId", "cpu1CoreId", "cpu2CoreId"]');
    expect(source).toContain('"c2000_runReloadAndDiagnose", "launch", "launch-workflow", ["sessionId", "cpu1CoreId", "cpu2CoreId", "cpu1OutPath", "cpu2OutPath"]');
    expect(source).toContain('"c2000_runFullDebugBundle", "launch", "launch-workflow", ["sessionId", "cpu1CoreId", "cpu2CoreId", "outputDir"]');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_runIpcAcceptance", ["cpu1CoreId", "cpu2CoreId", "ipcReadyExpressions[].coreId"])');
    expect(source).toContain('"postLaunchChecks.verifyRunPauseIsolation.cpu2CoreId"');
    expect(source).toContain('"postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary.steps[].commandCoreName"');
    expect(source).toContain("assert.deepEqual(requirement.expectedAdvancedAutomationToolContracts, expected.expectedAdvancedAutomationToolContracts)");
    expect(source).toContain('expectedCoreFields: ["coreName", "connected", "state", "pc", "loadedProgram", "loadedProgramInfo"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreFields, expected.expectedCoreFields)");
    expect(source).toContain("c2000_multicore_acceptance_evidence_plan");
    expect(source).toContain("continue_cpu1_only");
    expect(source).toContain("multicore_snapshot");
    expect(source).toContain("c2000_debug_boundary_ui_independence");
    expect(source).toContain("perCoreDebugSessionMethods.c2000_continue");
    expect(source).toContain("realAdapter.defaultBridge");
    expect(source).toContain("statelessDssCliBridgeUsedForDebugAutomation");
    expect(source).toContain("realAdapter.requiresResponseCoreIdentity");
    expect(source).toContain("assertCoreToolContract");
    expect(source).toContain('"c2000_runCore"');
    expect(source).toContain('"c2000_continue"');
    expect(source).toContain('"c2000_haltCore"');
    expect(source).toContain('"c2000_pause"');
    expect(source).toContain("responseCoreIdentityFields");
    expect(source).toContain('["coreId", "coreName"]');
    expect(source).toContain('["cores[].coreId", "cores[].coreName"]');
    expect(source).toContain('["acceptanceSummary.steps[].commandCoreId", "acceptanceSummary.steps[].commandCoreName"]');
    expect(source).toContain('"c2000_assignExpressions", "batch", "memory-write", ["sessionId", "assignments"], ["results[].coreId", "results[].coreName"]');
    expect(source).toContain('"c2000_injectFaults", "batch", "memory-write", ["sessionId", "faults"], ["results[].coreId", "results[].coreName"]');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_assignExpressions", ["assignments[].coreId"])');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_injectFaults", ["faults[].coreId"])');
    expect(source).toContain('"c2000_compareExpressions", "session", "target-read", ["sessionId", "comparisons"], ["comparisons[].left.coreId", "comparisons[].right.coreId"]');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_compareExpressions", ["comparisons[].left.coreId", "comparisons[].right.coreId"])');
    expect(source).toContain('"c2000_waitForExpressionSet", "session", "target-read", ["sessionId", "conditions", "timeoutMs"], ["conditions[].coreId"]');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_waitForExpressionSet", ["conditions[].coreId"])');
    expect(source).toContain('"c2000_diagnoseCpu2Boot", "session", "target-read", ["sessionId", "cpu1CoreId", "cpu2CoreId"], ["cpu1.coreId", "cpu2.coreId", "snapshot.cores[].coreId"]');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_diagnoseCpu2Boot", ["cpu1CoreId", "cpu2CoreId"])');
    expect(source).toContain('"c2000_launchMulticoreDebug", "launch", "launch-workflow", ["cores"], ["snapshot.cores[].coreId", "postLaunchActions.assignExpressions.results[].coreId"');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_launchMulticoreDebug", [');
    expect(source).toContain('"c2000_getSessionTopology", "session-read", ["sessionId"]');
    expect(source).toContain('"c2000_evaluateMany", "target-read", ["sessionId", "coreId", "expressions"]');
    expect(source).toContain('"c2000_getLoadedProgramInfo", "target-read", ["sessionId", "coreId"]');
    expect(source).toContain('"c2000_resolvePc", "target-read", ["sessionId", "coreId"]');
    expect(source).toContain('"c2000_resolveAddress", "target-read", ["sessionId", "coreId", "address"]');
    expect(source).toContain('"c2000_waitUntilExpression", "target-read", ["sessionId", "coreId", "expression", "expected", "timeoutMs"]');
    expect(source).toContain('"c2000_getMulticoreSnapshot"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_createDebugSession"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_connectTarget"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_connectCores"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_loadProgram"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_loadPrograms"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_continue"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_pause"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_reset"');
    expect(source).not.toContain('client.callTool({\n    name: "c2000_launchMulticoreDebug"');
  });

  test("prints blockers, readiness state, and the exact isolation command", async () => {
    const source = await readFile("scripts/ccs-acceptance-readiness.ts", "utf8");

    expect(source).toContain("blockers");
    expect(source).toContain("readyForHardwareAcceptance");
    expect(source).toContain("programDiscovery");
    expect(source).toContain("readiness.nextCommand");
    expect(source).toContain("assertNextHardwareAcceptanceCommand(readiness.nextCommand)");
    expect(source).toContain("function assertNextHardwareAcceptanceCommand");
    expect(source).toContain('assertEnvFlag(nextCommand, "C2000_RUN_LAUNCH")');
    expect(source).toContain('assertEnvFlag(nextCommand, "C2000_RUN_ISOLATION")');
    expect(source).toContain("npm run acceptance:ccs:mcp");
    expect(source).not.toContain("void nextCommandMarkers");
    expect(source).toContain("process.exitCode = readiness.readyForHardwareAcceptance ? 0 : 2");
  });
});
