import { readFile } from "node:fs/promises";
import { describe, expect, test } from "vitest";

describe("Direct hardware acceptance script contract", () => {
  test("keeps direct CCS hardware acceptance aligned with MCP stdio acceptance checks", async () => {
    const packageJson = JSON.parse(await readFile("package.json", "utf8")) as { scripts: Record<string, string> };
    const source = await readFile("scripts/ccs-hardware-acceptance.ts", "utf8");
    const helperSource = await readFile("src/debug/runPauseAcceptance.ts", "utf8");

    expect(packageJson.scripts["acceptance:ccs"]).toBe("tsx scripts/ccs-hardware-acceptance.ts");
    expect(source).toContain("tools.getDebugBoundary");
    expect(source).toContain("tools.getToolContracts");
    expect(source).toContain("assertToolContracts(contracts)");
    expect(source).toContain("tools.getAcceptanceEvidence");
    expect(source).toContain("assertDebugBoundary(debugBoundary)");
    expect(source).toContain("assertAcceptanceEvidence(acceptanceEvidence)");
    expect(source).toContain("buildUiIndependenceEvidence(debugBoundary)");
    expect(source).toContain("assertUiIndependenceEvidence(uiIndependenceEvidence)");
    expect(source).toContain("result.debugBoundary = debugBoundary");
    expect(source).toContain("result.toolContracts = contracts");
    expect(source).toContain("result.uiIndependenceEvidence = uiIndependenceEvidence");
    expect(source).toContain("result.acceptanceEvidence = acceptanceEvidence");
    expect(source.indexOf("tools.getDebugBoundary")).toBeLessThan(source.indexOf("tools.createDebugSession"));
    expect(source.indexOf("tools.getToolContracts")).toBeLessThan(source.indexOf("tools.createDebugSession"));
    expect(source.indexOf("tools.getAcceptanceEvidence")).toBeLessThan(source.indexOf("tools.createDebugSession"));
    expect(source).toContain("c2000_multicore_acceptance_evidence_plan");
    expect(source).toContain("continue_cpu1_only");
    expect(source).toContain("continue_cpu2_only");
    expect(source).toContain("pause_cpu1_only");
    expect(source).toContain("pause_cpu2_only");
    expect(source).toContain("multicore_snapshot");
    expect(source).toContain("debug_tool_contracts");
    expect(source).toContain("multicore_tool_contracts");
    expect(source).toContain("core_read_tool_contracts");
    expect(source).toContain("advanced_automation_contracts");
    expect(source).toContain("no_ccs_ui_click");
    expect(source).toContain("no_ccs_ui_focus");
    expect(source).toContain("officialTiMcpDebugControlsUsed");
    expect(source).toContain("activeTargetAllowed");
    expect(source).toContain("perCoreDebugSessionMethods.c2000_continue");
    expect(source).toContain("realAdapter.defaultBridge");
    expect(source).toContain("PersistentDssBridge");
    expect(source).toContain("statelessDssCliBridgeUsedForDebugAutomation");
    expect(source).toContain("session.target.runAsynch()");
    expect(source).toContain("session.memory.loadProgram(programUri)");
    expect(source).toContain("discoverAcceptancePrograms");
    expect(source).toContain("programDiscovery");
    expect(source).toContain("C2000_PROGRAM_SEARCH_ROOTS");
    expect(source).toContain("workspace_ccstheia");
    expect(source).toContain("debugProcessDetails");
    expect(source).toContain("formatDebugProcessOwners");
    expect(source).toContain("tools.getSessionTopology");
    expect(source).toContain("assertSessionTopology(topology)");
    expect(source).toContain("result.topology = topology");
    expect(source).toContain("topology.adapterSessionId");
    expect(source).toContain("topology.debugSessionRoute");
    expect(source).toContain("core0.debugSessionKey");
    expect(source).toContain("core2.debugSessionKey");
    expect(source.indexOf("tools.getSessionTopology")).toBeLessThan(source.indexOf("tools.connectCores"));
    expect(source).toContain('assertBatchCoreResults("c2000_connectCores", connect, [0, 2])');
    expect(source).toContain('assertBatchCoreResults("c2000_loadPrograms", load, [0, 2])');
    expect(source).toContain("assertSnapshotCoreState(initialSnapshot, [0, 2])");
    expect(source).toContain("assertSnapshotCoreIdentity(snapshot, coreId)");
    expect(source).toContain("function assertSnapshotCoreIdentity");
    expect(source).toContain("assert.equal(core.coreName, expectedCoreName(coreId)");
    expect(source).toContain("function expectedCoreName");
    expect(source).toContain("assertSnapshotLoadedPrograms(initialSnapshot, cpu1Program, cpu2Program)");
    expect(source).toContain("core.loadedProgramInfo?.programUri");
    expect(source).toContain("core.loadedProgramInfo?.coreId");
    expect(source).toContain("core.loadedProgramInfo?.sha256");
    expect(source).toContain("core.loadedProgramInfo?.symbolsLoaded");
    expect(source).toContain('assert.equal(core.state, "Halted", `core ${coreId} state`)');
    expect(source).toContain("assertAcceptanceSummaryWithEvidence(isolation.acceptanceSummary, result)");
    expect(source).toContain('assertRunPauseAcceptanceSummary as assertAcceptanceSummary');
    expect(source).not.toContain("function assertAcceptanceSummary(summary");
    expect(source).toContain("assertAcceptanceSummary");
    expect(source).toContain("result.acceptanceSummary");
    expect(source).toContain("result.acceptanceSummary = isolation.acceptanceSummary");
    expect(source.indexOf("result.isolation = isolation")).toBeLessThan(source.indexOf("assertAcceptanceSummaryWithEvidence(isolation.acceptanceSummary, result)"));
    expect(source).toContain("assertAcceptanceSummaryWithEvidence(isolation.acceptanceSummary, result)");
    expect(source).toContain("printFailureEvidence(evidence, error)");
    expect(source).not.toContain("?? buildAcceptanceSummary");
    expect(source).toContain('const runLaunch = process.env.C2000_RUN_LAUNCH === "1"');
    expect(source).toContain('mode: modeName(runIsolation, runLaunch)');
    expect(source).toContain("tools.launchMulticoreDebug");
    expect(source).toContain("tools.injectFaults");
    expect(source).toContain('sessionName: "f28p65x-hardware-launch-acceptance"');
    expect(source).toContain("programDiscovery: {");
    expect(source).toContain("enabled: true");
    expect(source).toContain("assert.equal(launch.programDiscovery.cpu1.selected, cpu1Program)");
    expect(source).toContain("assert.equal(launch.programDiscovery.cpu2.selected, cpu2Program)");
    expect(source).not.toContain('programUri: cpu1Program, connect: true, load: true');
    expect(source).not.toContain('programUri: cpu2Program, connect: true, load: true');
    expect(source).toContain("postLaunchChecks: runIsolation ? { verifyRunPauseIsolation: {} } : undefined");
    expect(source).toContain("assertSnapshotCoreState(launch.snapshot, [0, 2])");
    expect(source).toContain("assertSnapshotLoadedPrograms(launch.snapshot, cpu1Program, cpu2Program)");
    expect(source).toContain("assertAcceptanceSummaryWithEvidence(launch.postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary, result)");
    expect(source.indexOf("result.launch = launch")).toBeLessThan(source.indexOf("assertAcceptanceSummaryWithEvidence(launch.postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary, result)"));
    expect(source.indexOf("result.launchAcceptanceSummary = launch.postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary")).toBeLessThan(source.indexOf("assertAcceptanceSummaryWithEvidence(launch.postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary, result)"));
    expect(source).toContain("result.launch = launch");
    expect(source).toContain("function assertSuccessWithEvidence");
    expect(source).toContain("printFailureEvidence({ ...evidence, failedToolResult: result }, error)");
    expect(source.indexOf("result.isolation = isolation")).toBeLessThan(source.indexOf('assertSuccessWithEvidence("c2000_verifyRunPauseIsolation", isolation, result, { initialSnapshot })'));
    expect(source.indexOf("result.launch = launch")).toBeLessThan(source.indexOf('assertSuccessWithEvidence("c2000_launchMulticoreDebug", launch, result, { preflight })'));
    expect(source).toContain("result.programDiscovery = programDiscovery");
    expect(source).toContain("let launchSessionId: string | undefined");
    expect(source).toContain("await tools.closeDebugSession({ sessionId: launchSessionId })");
    expect(source).toContain('"c2000_runCore", "core", "execution-control", ["sessionId", "coreId"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_continue", "core", "execution-control", ["sessionId", "coreId"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_haltCore", "core", "execution-control", ["sessionId", "coreId"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_loadPrograms", "batch", "program-load", ["sessionId", "programs"], ["results[].coreId", "results[].coreName"]');
    expect(source).toContain('"c2000_assignExpressions", "batch", "memory-write", ["sessionId", "assignments"], ["results[].coreId", "results[].coreName"]');
    expect(source).toContain('"c2000_evaluateMany", "core", "target-read", ["sessionId", "coreId", "expressions"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_getLoadedProgramInfo", "core", "target-read", ["sessionId", "coreId"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_resolvePc", "core", "target-read", ["sessionId", "coreId"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_resolveAddress", "core", "target-read", ["sessionId", "coreId", "address"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_waitUntilExpression", "core", "target-read", ["sessionId", "coreId", "expression", "expected", "timeoutMs"], ["coreId", "coreName"]');
    expect(source).toContain('"c2000_compareExpressions", "session", "target-read", ["sessionId", "comparisons"], ["comparisons[].left.coreId", "comparisons[].right.coreId"]');
    expect(source).toContain('"c2000_waitForExpressionSet", "session", "target-read", ["sessionId", "conditions", "timeoutMs"], ["conditions[].coreId"]');
    expect(source).toContain('"c2000_diagnoseCpu2Boot", "session", "target-read", ["sessionId", "cpu1CoreId", "cpu2CoreId"], ["cpu1.coreId", "cpu2.coreId", "snapshot.cores[].coreId"]');
    expect(source).toContain('"c2000_launchMulticoreDebug", "launch", "launch-workflow", ["cores"], ["snapshot.cores[].coreId", "postLaunchActions.assignExpressions.results[].coreId"');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_assignExpressions", ["assignments[].coreId"])');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_compareExpressions", ["comparisons[].left.coreId", "comparisons[].right.coreId"])');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_diagnoseCpu2Boot", ["cpu1CoreId", "cpu2CoreId"])');
    expect(source).toContain('assertCoreIdentityFields(contracts, "c2000_launchMulticoreDebug", [');
    expect(helperSource).toContain('assert.equal(acceptanceSummary.evidence, RUN_PAUSE_ACCEPTANCE_EVIDENCE)');
    expect(helperSource).toContain("assert.deepEqual(acceptanceSummary.requiredLabels");
    expect(helperSource).toContain('{ label: "c2000_continue(cpu1)", targetCoreId: 0, targetCoreName: "C28xx_CPU1", expectedTargetState: "Running", peerCoreIds: [2] }');
    expect(helperSource).toContain("step.commandCoreId");
    expect(helperSource).toContain("step.commandCoreName");
    expect(helperSource).toContain("commandCoreId mismatch");
    expect(helperSource).toContain("commandCoreName mismatch");
    expect(helperSource).toContain("targetCoreName");
    expect(helperSource).toContain("assert.deepEqual(step.peerCoreIds");
    expect(helperSource).toContain("assert.equal(step.failures.length, 0");
  });

  test("does not let cleanup failures hide the primary hardware acceptance failure", async () => {
    const source = await readFile("scripts/ccs-hardware-acceptance.ts", "utf8");

    expect(source).toContain("let primaryError: unknown");
    expect(source).toContain("primaryError = error");
    expect(source).toContain("await tools.closeDebugSession({ sessionId })");
    expect(source).toContain("if (primaryError)");
    expect(source).toContain("c2000_closeDebugSession cleanup failed after primary failure");
    expect(source).toContain("throw cleanupError");
  });

  test("uses configurable DSS timeout for direct CCS scripting acceptance", async () => {
    const source = await readFile("scripts/ccs-hardware-acceptance.ts", "utf8");

    expect(source).toContain('const dssTimeoutMs = Number.parseInt(process.env.C2000_MCP_DSS_TIMEOUT_MS ?? "300000", 10)');
    expect(source).toContain('import { resolveCcxmlPath, resolveCcsInstallPath } from "../src/ccs/paths.js"');
    expect(source).toContain("const ccsInstallPath = resolveCcsInstallPath()");
    expect(source).toContain("new CcsScriptingAdapter({ ccsInstallPath, dssTimeoutMs })");
  });
});
