import { readFile } from "node:fs/promises";
import { describe, expect, test } from "vitest";

describe("MCP stdio smoke script contract", () => {
  test("loads CPU1/CPU2 programs through MCP and verifies snapshot loadedProgram metadata", async () => {
    const source = await readFile("scripts/mcp-stdio-smoke.ts", "utf8");
    const helperSource = await readFile("src/debug/runPauseAcceptance.ts", "utf8");

    expect(source).toContain('"c2000_getDebugBoundary"');
    expect(source).toContain('name: "c2000_getDebugBoundary"');
    expect(source).toContain('"c2000_getAcceptanceEvidence"');
    expect(source).toContain('name: "c2000_getAcceptanceEvidence"');
    expect(source).toContain("acceptanceEvidence.evidence");
    expect(source).toContain("c2000_multicore_acceptance_evidence_plan");
    expect(source).toContain("acceptanceEvidence.requirements");
    expect(source).toContain("continue_cpu1_only");
    expect(source).toContain("checkedCommandFields");
    expect(source).toContain('"debug_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain('expectedCoreDebugTools: ["c2000_connectTarget", "c2000_disconnectTarget", "c2000_runCore", "c2000_continue", "c2000_haltCore", "c2000_pause", "c2000_reset", "c2000_getTargetState", "c2000_loadProgram", "c2000_loadSymbols"]');
    expect(source).toContain('expectedRequiredInputs: ["sessionId", "coreId"]');
    expect(source).toContain('expectedResponseCoreIdentityFields: ["coreId", "coreName"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreDebugTools, expected.expectedCoreDebugTools)");
    expect(source).toContain('"multicore_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedMulticoreToolContracts");
    expect(source).toContain('name: "c2000_loadPrograms"');
    expect(source).toContain('coreIdentityFields: ["programs[].coreId"]');
    expect(source).toContain('name: "c2000_getMulticoreSnapshot"');
    expect(source).toContain('responseCoreIdentityFields: ["cores[].coreId", "cores[].coreName"]');
    expect(source).toContain('"core_read_tool_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedCoreReadToolContracts");
    expect(source).toContain('name: "c2000_evaluateMany"');
    expect(source).toContain('name: "c2000_getLoadedProgramInfo"');
    expect(source).toContain('name: "c2000_resolvePc"');
    expect(source).toContain('name: "c2000_resolveAddress"');
    expect(source).toContain('name: "c2000_waitUntilExpression"');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreReadToolContracts, expected.expectedCoreReadToolContracts)");
    expect(source).toContain('"advanced_automation_contracts", "c2000_getToolContracts"');
    expect(source).toContain("expectedAdvancedAutomationToolContracts");
    expect(source).toContain('name: "c2000_assignExpressions"');
    expect(source).toContain('targetEffect: "memory-write"');
    expect(source).toContain('coreIdentityFields: ["assignments[].coreId"]');
    expect(source).toContain('name: "c2000_waitForExpressionSet"');
    expect(source).toContain('coreIdentityFields: ["conditions[].coreId"]');
    expect(source).toContain('name: "c2000_diagnoseCpu2Boot"');
    expect(source).toContain('responseCoreIdentityFields: ["cpu1.coreId", "cpu2.coreId", "snapshot.cores[].coreId"]');
    expect(source).toContain('name: "c2000_diagnoseBootHandoff"');
    expect(source).toContain('name: "c2000_waitForIpcReady"');
    expect(source).toContain('name: "c2000_reloadResetRunToMain"');
    expect(source).toContain('name: "c2000_runIpcAcceptance"');
    expect(source).toContain('name: "c2000_runBootHandoffDiagnosis"');
    expect(source).toContain('name: "c2000_runReloadAndDiagnose"');
    expect(source).toContain('name: "c2000_runFullDebugBundle"');
    expect(source).toContain('coreIdentityFields: ["cpu1CoreId", "cpu2CoreId", "ipcReadyExpressions[].coreId"]');
    expect(source).toContain('responseCoreIdentityFields: ["snapshot.cores[].coreId", "ipcReady.conditions[].coreId", "diagnosis.cpu1.coreId", "diagnosis.cpu2.coreId", "diagnosis.snapshot.cores[].coreId", "ramOwnership.maps[].coreId"]');
    expect(source).toContain("runToMainSupported");
    expect(source).toContain("runToMainAchieved");
    expect(source).toContain("unsupportedReason.includes(\"breakpoint\")");
    expect(source).toContain('name: "c2000_launchMulticoreDebug"');
    expect(source).toContain('"postLaunchChecks.verifyRunPauseIsolation.cpu2CoreId"');
    expect(source).toContain('"postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary.steps[].commandCoreName"');
    expect(source).toContain("assert.deepEqual(requirement.expectedAdvancedAutomationToolContracts, expected.expectedAdvancedAutomationToolContracts)");
    expect(source).toContain("multicore_snapshot");
    expect(source).toContain('expectedCoreFields: ["coreName", "connected", "state", "pc", "loadedProgram", "loadedProgramInfo"]');
    expect(source).toContain("assert.deepEqual(requirement.expectedCoreFields, expected.expectedCoreFields)");
    expect(source).toContain("no_ccs_ui_focus");
    expect(source).toContain('"c2000_discoverAcceptancePrograms"');
    expect(source).toContain('name: "c2000_discoverAcceptancePrograms"');
    expect(source).toContain('"c2000_getAcceptanceReadiness"');
    expect(source).toContain('name: "c2000_getAcceptanceReadiness"');
    expect(source).toContain('"c2000_analyzeRamOwnership"');
    expect(source).toContain('name: "c2000_analyzeRamOwnership"');
    expect(source).toContain("ramOwnership.ownershipActions[0].memoryRegion");
    expect(source).toContain('assert.equal(discoveryContract.inputScope, "host")');
    expect(source).toContain("acceptanceReadiness.readyForHardwareAcceptance");
    expect(source).toContain("acceptanceReadiness.debugBoundary.officialTiMcpDebugControlsUsed");
    expect(source).toContain("acceptanceReadiness.uiIndependenceEvidence");
    expect(source).toContain("acceptanceReadiness.uiIndependenceEvidence.evidence");
    expect(source).toContain("acceptanceReadiness.uiIndependenceEvidence.requiredPerCoreInputs");
    expect(source).toContain("acceptanceReadiness.programDiscovery.cpu1.selected");
    expect(source).toContain("acceptanceReadiness.programDiscovery.cpu2.selected");
    expect(source).toContain("programDiscovery.cpu1.selected");
    expect(source).toContain("programDiscovery.cpu2.selected");
    expect(source).toContain("officialTiMcpDebugControlsUsed");
    expect(source).toContain("activeTargetAllowed");
    expect(source).toContain("perCoreDebugSessionMethods.c2000_continue");
    expect(source).toContain("realAdapter.defaultBridge");
    expect(source).toContain("PersistentDssBridge");
    expect(source).toContain("statelessDssCliBridgeUsedForDebugAutomation");
    expect(source).toContain("realAdapter.requiresResponseCoreIdentity");
    expect(source).toContain("session.target.runAsynch()");
    expect(source).toContain("session.memory.loadProgram(programUri)");
    expect(source).toContain("debugBoundary");
    expect(source).toContain('name: "c2000_loadPrograms"');
    expect(source).toContain('name: "c2000_getSessionTopology"');
    expect(source).toContain('name: "c2000_loadProgram"');
    expect(source).toContain('name: "c2000_getTargetState"');
    expect(source).toContain('name: "c2000_runCore"');
    expect(source).toContain('name: "c2000_haltCore"');
    expect(source).toContain('name: "c2000_reset"');
    expect(source).toContain('name: "c2000_disconnectTarget"');
    expect(source).toContain('name: "c2000_assignExpressions"');
    expect(source).toContain('name: "c2000_injectFaults"');
    expect(source).toContain('name: "c2000_getLoadedProgramInfo"');
    expect(source).toContain('name: "c2000_resolvePc"');
    expect(source).toContain('name: "c2000_resolveAddress"');
    expect(source).toContain('name: "c2000_waitUntilExpression"');
    expect(source).toContain('name: "c2000_verifyRunPauseIsolation"');
    expect(source).toContain('name: "c2000_launchMulticoreDebug"');
    expect(source).toContain("programDiscovery: {");
    expect(source).toContain("enabled: true");
    expect(source).toContain("launch.programDiscovery.cpu1.selected");
    expect(source).toContain("launch.programDiscovery.cpu2.selected");
    expect(source).toContain("const cpu1ReloadOut");
    expect(source).toContain("const launchCpu1Out");
    expect(source).toContain("const launchCpu2Out");
    expect(source).toContain("targetSelector");
    expect(source).toContain("topology.adapterSessionId");
    expect(source).toContain("topology.debugSessionRoute");
    expect(source).toContain("debugSessionKey");
    expect(source).toContain("assertCoreLoadedProgram(snapshot, 0, cpu1ReloadOut)");
    expect(source).toContain("assertCoreLoadedProgram(snapshot, 0, cpu1Out)");
    expect(source).toContain("assertCoreLoadedProgram(snapshot, 2, cpu2Out)");
    expect(source).toContain("assertCoreLoadedProgram(launch.snapshot, 0, launchCpu1Out)");
    expect(source).toContain("assertCoreLoadedProgram(launch.snapshot, 2, launchCpu2Out)");
    expect(source).toContain("assertSnapshotCoreIdentity(snapshot, coreId)");
    expect(source).toContain("function assertSnapshotCoreIdentity");
    expect(source).toContain("assert.equal(core.coreName, expectedCoreName(coreId)");
    expect(source).toContain("function expectedCoreName");
    expect(source).toContain("g_ulHybrid30kLaunchBatchFault");
    expect(source).toContain("g_ulHybrid30kLaunchInjectedFault");
    expect(source).toContain("launch.postLaunchActions.assignExpressions");
    expect(source).toContain("launch.postLaunchActions.injectFaults");
    expect(source).toContain("launch.postLaunchChecks.compareExpressions.matched");
    expect(source).toContain("core.loadedProgramInfo?.programUri");
    expect(source).toContain("core.loadedProgramInfo?.sha256");
    expect(source).toContain('assert.equal(cpu1State.state, "Running")');
    expect(source).toContain('assert.equal(cpu1RunAlias.state, "Running")');
    expect(source).toContain('assert.equal(cpu1HaltAlias.state, "Halted")');
    expect(source).toContain('assert.equal(cpu1Reset.state, "Halted")');
    expect(source).toContain('assert.equal(cpu2Disconnect.connected, false)');
    expect(source).toContain("g_ulHybrid30kBatchFault");
    expect(source).toContain("batchAssignmentReadbackCpu1");
    expect(source).toContain("batchAssignmentReadbackCpu2");
    expect(source).toContain("assertCoreReadIdentity(batchAssignmentReadbackCpu1, 0)");
    expect(source).toContain("assertCoreReadIdentity(batchAssignmentReadbackCpu2, 2)");
    expect(source).toContain("g_ulHybrid30kInjectedFault");
    expect(source).toContain("injectedFaultReadbackCpu1");
    expect(source).toContain("injectedFaultReadbackCpu2");
    expect(source).toContain("assertCoreReadIdentity(injectedFaultReadbackCpu1, 0)");
    expect(source).toContain("assertCoreReadIdentity(injectedFaultReadbackCpu2, 2)");
    expect(source).toContain("cpu1LoadedProgramInfo");
    expect(source).toContain("cpu2LoadedProgramInfo");
    expect(source).toContain("cpu1ResolvedPc");
    expect(source).toContain("cpu2ResolvedPc");
    expect(source).toContain("cpu1ResolvedAddress");
    expect(source).toContain("cpu2WaitUntilExpression");
    expect(source).toContain("assertCoreReadIdentity(cpu1LoadedProgramInfo, 0)");
    expect(source).toContain("assertCoreReadIdentity(cpu2LoadedProgramInfo, 2)");
    expect(source).toContain("assertCoreReadIdentity(cpu1ResolvedPc, 0)");
    expect(source).toContain("assertCoreReadIdentity(cpu2ResolvedPc, 2)");
    expect(source).toContain("assertPartialAddressResolution(cpu1ResolvedAddress");
    expect(source).toContain("assertCoreReadIdentity(cpu2WaitUntilExpression, 2)");
    expect(source).toContain("function assertCoreReadIdentity");
    expect(source).toContain("assertAcceptanceSummary(runPauseIsolation.acceptanceSummary)");
    expect(source).toContain("assertAcceptanceSummary(launch.postLaunchChecks.verifyRunPauseIsolation.acceptanceSummary)");
    expect(source).toContain('assertRunPauseAcceptanceSummary as assertAcceptanceSummary');
    expect(source).not.toContain("function assertAcceptanceSummary");
    expect(helperSource).toContain('assert.equal(acceptanceSummary.evidence, RUN_PAUSE_ACCEPTANCE_EVIDENCE)');
    expect(helperSource).toContain("assert.deepEqual(acceptanceSummary.requiredLabels");
    expect(helperSource).toContain('{ label: "c2000_continue(cpu1)", targetCoreId: 0, targetCoreName: "C28xx_CPU1", expectedTargetState: "Running", peerCoreIds: [2] }');
    expect(source).toContain('assert.equal(continueContract.targetEffect, "execution-control")');
    expect(source).toContain('assert.deepEqual(continueContract.coreIdentityFields, ["coreId"])');
    expect(source).toContain('assert.deepEqual(continueContract.responseCoreIdentityFields, ["coreId", "coreName"])');
    expect(source).toContain('assert.equal(preflightContract.targetEffect, "host-read")');
    expect(source).toContain('assert.equal(boundaryContract.targetEffect, "host-read")');
    expect(source).toContain('assert.equal(loadProgramsContract.targetEffect, "program-load")');
    expect(source).toContain('assert.deepEqual(loadProgramsContract.coreIdentityFields, ["programs[].coreId"])');
    expect(source).toContain('assert.deepEqual(loadProgramsContract.responseCoreIdentityFields, ["results[].coreId", "results[].coreName"])');
    expect(source).toContain('assert.deepEqual(snapshotContract.coreIdentityFields, ["coreIds[]"])');
    expect(source).toContain('assert.deepEqual(snapshotContract.responseCoreIdentityFields, ["cores[].coreId", "cores[].coreName"])');
    expect(source).toContain('assert.deepEqual(runPauseContract.coreIdentityFields, ["cpu1CoreId", "cpu2CoreId"])');
    expect(source).toContain('assert.deepEqual(runPauseContract.responseCoreIdentityFields, ["acceptanceSummary.steps[].commandCoreId", "acceptanceSummary.steps[].commandCoreName"])');
    expect(source).toContain('assert.deepEqual(assignExpressionsContract.responseCoreIdentityFields, ["results[].coreId", "results[].coreName"])');
    expect(source).toContain('assert.deepEqual(injectFaultsContract.responseCoreIdentityFields, ["results[].coreId", "results[].coreName"])');
    expect(source).toContain('assert.deepEqual(compareExpressionsContract.responseCoreIdentityFields, ["comparisons[].left.coreId", "comparisons[].right.coreId"])');
    expect(source).toContain('assert.deepEqual(waitForExpressionSetContract.responseCoreIdentityFields, ["conditions[].coreId"])');
    expect(source).toContain('assert.deepEqual(diagnoseCpu2BootContract.responseCoreIdentityFields, ["cpu1.coreId", "cpu2.coreId", "snapshot.cores[].coreId"])');
    expect(source).toContain("assertCoreIdentityFields(launchContract");
    expect(source).toContain("assertCoreIdentityFields(launchContract.responseCoreIdentityFields");
  });
});
