################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
project/hybrid30k/board/src/board_cla_adc.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_cla_adc.cla $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_cla_pwm.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_cla_pwm.cla $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_cpu1.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_cpu1.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_cpu1_isr.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_cpu1_isr.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_cpu1_safety.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_cpu1_safety.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_mux.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_mux.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_profile.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_profile.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/board/src/board_relay.obj: C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/board_relay.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/generated/dk8_prod/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --preinclude="C:/Users/11981/Documents/Hybrid_Platform-integration-dk9-mil-hw-rework-review-20260902/project/hybrid30k/board/src/dk8_device_clocktree.h" --define=_FLASH --define=BOARD_PROFILE_DK8_PROD --define=DEBUG --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/board/src/$(basename $(<F)).d_raw" --include_path="C:/Users/11981/Documents/C2000_Debug_MCP/ccs_ws_integration_dk9_mil_corrected_20260902/Hybrid30K_CPU1_DK8_PROD/CPU1_FLASH/syscfg" --obj_directory="project/hybrid30k/board/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '


