################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
project/hybrid30k/dsp/cpu1/src/cpu1_core_comm.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_core_comm.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_ctrl.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_ctrl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_ctrl_runtime_boundary_validation.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/validation/dk9/cpu1/cpu1_ctrl_runtime_boundary_validation.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_measurement.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_measurement.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_param.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_param.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_safety_validation.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/validation/dk9/cpu1/cpu1_safety_validation.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_stack_watch.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_stack_watch.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/cpu1_stack_watch_sp.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/cpu1_stack_watch_sp.asm $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/main_cpu1_validation.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/validation/dk9/cpu1/main_cpu1_validation.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '

project/hybrid30k/dsp/cpu1/src/rtm_cpu1_param.obj: C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/dsp/cpu1/src/rtm_cpu1_param.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'C2000 Compiler: "$<"'
	"D:/ccs21.0/ccs/tools/compiler/ti-cgt-c2000_25.11.1.LTS/bin/cl2000" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/board.opt" --cmd_file="C:/Users/11981/Documents/Hybrid_Platform/.worktrees/dk9-mil-hw-rework-corrected-20260902/project/hybrid30k/board/generated/dk9_comm_validation/cpu1/c2000ware_libraries.opt" --cmd_file="ccsIncludes.opt"  -v28 -ml -mt --cla_support=cla2 --float_support=fpu64 --isr_save_vcu_regs=off --tmu_support=tmu1 --vcu_support=vcrc -O2 --define=RAM --define=HYBRID30K_DK9_SAFE_VALIDATION --define=HYBRID30K_DK9_COMM_VALIDATION --define=HYBRID30K_DK9_MIL_VALIDATION --define=HYBRID30K_DK9_VALIDATION_DEBUG_UART --define=HYBRID30K_DK9_DC_SIDE_PIN_TEST --define=HYBRID30K_DK9_TRIP_INJECTION --define=STACK_WATCH_ENABLE --define=SCHED_CPU1_VALIDATION_HOOK_ENABLE --define=DEBUG --define=BOARD_PROFILE_DK9_LAUNCHXL --define=CPU1 --diag_suppress=10063 --diag_warning=225 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --preproc_with_compile --preproc_dependency="project/hybrid30k/dsp/cpu1/src/$(basename $(<F)).d_raw" --obj_directory="project/hybrid30k/dsp/cpu1/src" $(GEN_OPTS__FLAG) "$<"
	@echo ' '


