#ifndef RTM_CTRL_MODEL_VALUES_H_
#define RTM_CTRL_MODEL_VALUES_H_

/* Generated dual-core control values for the selected model. */
#define RTM_CTRL_VALUE_UI_DC_VOLT_MAX  8750UL
#define RTM_CTRL_VALUE_I_INV_CURR_MAX  7433L
#define RTM_CTRL_VALUE_UL_GRID_VOLT_SCALE_Q12  4096UL
#define RTM_CTRL_VALUE_UL_INV_VOLT_SCALE_Q12  4096UL
#define RTM_CTRL_VALUE_UI_GRID_OVER_VOLT_LMT1  2800UL
#define RTM_CTRL_VALUE_UI_GRID_UNDER_VOLT_LMT1  1700UL
#define RTM_CTRL_VALUE_UI_GRID_OVER_FREQ_LMT1  6300UL
#define RTM_CTRL_VALUE_UI_GRID_UNDER_FREQ_LMT1  5700UL
#define RTM_CTRL_VALUE_I_CURR_PI_KP_D_Q12  16200L
#define RTM_CTRL_VALUE_I_CURR_PI_KI_D  2209L
#define RTM_CTRL_VALUE_I_CURR_PI_KP_Q_Q12  16200L
#define RTM_CTRL_VALUE_I_CURR_PI_KI_Q  2209L
#define RTM_CTRL_VALUE_I_CURR_PI_KP0_Q12  16200L
#define RTM_CTRL_VALUE_I_CURR_PI_KI0  2209L
#define RTM_CTRL_VALUE_I_CURR_DQI_LMT_Q12  4300L
#define RTM_CTRL_VALUE_I_CURR_VOLT_FWD_MAX_Q12  4300L
#define RTM_CTRL_VALUE_UI_INV_PWM_MODE  0UL
#define RTM_CTRL_VALUE_UI_VOLT_LOOP_CALIBRATED  0UL
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KBASE_Q12  3277L
#define RTM_CTRL_VALUE_I_VOLT_VIRTUAL_R_Q12  0L
#define RTM_CTRL_VALUE_I_OFFGRID_FREQ_REF  6000L
#define RTM_CTRL_VALUE_I_VOLT_OUT_MIN_Q12  -32767L
#define RTM_CTRL_VALUE_I_VOLT_OUT_MAX_Q12  32767L
#define RTM_CTRL_VALUE_I_VOLT_CURRENT_REF_MAX_Q12  4300L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KP_D_Q12  1400L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI_D_NORMAL  1000L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI_D_FAST  1000L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KP_Q_Q12  1400L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI_Q_NORMAL  1000L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI_Q_FAST  1000L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KP0_Q12  900L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI0_NORMAL  0L
#define RTM_CTRL_VALUE_I_VOLT_DQ0_KI0_FAST  0L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KP_A_Q12  2789L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_A_NORMAL  1992L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_A_FAST  1992L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KP_B_Q12  2789L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_B_NORMAL  1992L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_B_FAST  1992L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KP_C_Q12  2789L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_C_NORMAL  1992L
#define RTM_CTRL_VALUE_I_VOLT_RMS_KI_C_FAST  1992L
#define RTM_CTRL_VALUE_I_VOLT_SYNC_LPF_Q12  0L
#define RTM_CTRL_VALUE_I_VOLT_SYNC_RAMP_Q12  0L
#define RTM_CTRL_VALUE_I_VOLT_RMS_RAMP_Q12  0L
#define RTM_CTRL_VALUE_UI_VBUS_MID_HOLD_CNT  90UL
#define RTM_CTRL_VALUE_UI_VBUS_MID_ADJUST_CNT  2000UL
#define RTM_CTRL_VALUE_I_VBUS_MID_THRESHOLD  0L

/* Rated Derived bootstrap values; CPU2 is the runtime authority. */
#define RTM_CTRL_VALUE_I_PHASE_VOLT_RMS_BASE  1386L
#define RTM_CTRL_VALUE_I_PHASE_CURR_RMS_BASE  7217L
#define RTM_CTRL_VALUE_I_OMEGA_L_Q12  80L
#define RTM_CTRL_VALUE_I_PLL_FREQ_NOM  6000L

#define RTM_CTRL_PARAMETER_MODEL_INITIALIZER \
    { \
        .uiDcVoltMax = RTM_CTRL_VALUE_UI_DC_VOLT_MAX, \
        .iInvCurrMax = RTM_CTRL_VALUE_I_INV_CURR_MAX, \
        .ulGridVoltScale_Q12 = RTM_CTRL_VALUE_UL_GRID_VOLT_SCALE_Q12, \
        .ulInvVoltScale_Q12 = RTM_CTRL_VALUE_UL_INV_VOLT_SCALE_Q12, \
        .uiGridOverVoltLmt1 = RTM_CTRL_VALUE_UI_GRID_OVER_VOLT_LMT1, \
        .uiGridUnderVoltLmt1 = RTM_CTRL_VALUE_UI_GRID_UNDER_VOLT_LMT1, \
        .uiGridOverFreqLmt1 = RTM_CTRL_VALUE_UI_GRID_OVER_FREQ_LMT1, \
        .uiGridUnderFreqLmt1 = RTM_CTRL_VALUE_UI_GRID_UNDER_FREQ_LMT1, \
        .iCurrPIKpD_Q12 = RTM_CTRL_VALUE_I_CURR_PI_KP_D_Q12, \
        .iCurrPIKiD = RTM_CTRL_VALUE_I_CURR_PI_KI_D, \
        .iCurrPIKpQ_Q12 = RTM_CTRL_VALUE_I_CURR_PI_KP_Q_Q12, \
        .iCurrPIKiQ = RTM_CTRL_VALUE_I_CURR_PI_KI_Q, \
        .iCurrPIKp0_Q12 = RTM_CTRL_VALUE_I_CURR_PI_KP0_Q12, \
        .iCurrPIKi0 = RTM_CTRL_VALUE_I_CURR_PI_KI0, \
        .iCurrDQILmt_Q12 = RTM_CTRL_VALUE_I_CURR_DQI_LMT_Q12, \
        .iCurrVoltFwdMax_Q12 = RTM_CTRL_VALUE_I_CURR_VOLT_FWD_MAX_Q12, \
        .uiInvPwmMode = RTM_CTRL_VALUE_UI_INV_PWM_MODE, \
        .uiVoltLoopCalibrated = RTM_CTRL_VALUE_UI_VOLT_LOOP_CALIBRATED, \
        .iVoltDq0Kbase_Q12 = RTM_CTRL_VALUE_I_VOLT_DQ0_KBASE_Q12, \
        .iVoltVirtualR_Q12 = RTM_CTRL_VALUE_I_VOLT_VIRTUAL_R_Q12, \
        .iOffgridFreqRef = RTM_CTRL_VALUE_I_OFFGRID_FREQ_REF, \
        .iVoltOutMin_Q12 = RTM_CTRL_VALUE_I_VOLT_OUT_MIN_Q12, \
        .iVoltOutMax_Q12 = RTM_CTRL_VALUE_I_VOLT_OUT_MAX_Q12, \
        .iVoltCurrentRefMax_Q12 = RTM_CTRL_VALUE_I_VOLT_CURRENT_REF_MAX_Q12, \
        .iVoltDq0KpD_Q12 = RTM_CTRL_VALUE_I_VOLT_DQ0_KP_D_Q12, \
        .iVoltDq0KiDNormal = RTM_CTRL_VALUE_I_VOLT_DQ0_KI_D_NORMAL, \
        .iVoltDq0KiDFast = RTM_CTRL_VALUE_I_VOLT_DQ0_KI_D_FAST, \
        .iVoltDq0KpQ_Q12 = RTM_CTRL_VALUE_I_VOLT_DQ0_KP_Q_Q12, \
        .iVoltDq0KiQNormal = RTM_CTRL_VALUE_I_VOLT_DQ0_KI_Q_NORMAL, \
        .iVoltDq0KiQFast = RTM_CTRL_VALUE_I_VOLT_DQ0_KI_Q_FAST, \
        .iVoltDq0Kp0_Q12 = RTM_CTRL_VALUE_I_VOLT_DQ0_KP0_Q12, \
        .iVoltDq0Ki0Normal = RTM_CTRL_VALUE_I_VOLT_DQ0_KI0_NORMAL, \
        .iVoltDq0Ki0Fast = RTM_CTRL_VALUE_I_VOLT_DQ0_KI0_FAST, \
        .iVoltRmsKpA_Q12 = RTM_CTRL_VALUE_I_VOLT_RMS_KP_A_Q12, \
        .iVoltRmsKiANormal = RTM_CTRL_VALUE_I_VOLT_RMS_KI_A_NORMAL, \
        .iVoltRmsKiAFast = RTM_CTRL_VALUE_I_VOLT_RMS_KI_A_FAST, \
        .iVoltRmsKpB_Q12 = RTM_CTRL_VALUE_I_VOLT_RMS_KP_B_Q12, \
        .iVoltRmsKiBNormal = RTM_CTRL_VALUE_I_VOLT_RMS_KI_B_NORMAL, \
        .iVoltRmsKiBFast = RTM_CTRL_VALUE_I_VOLT_RMS_KI_B_FAST, \
        .iVoltRmsKpC_Q12 = RTM_CTRL_VALUE_I_VOLT_RMS_KP_C_Q12, \
        .iVoltRmsKiCNormal = RTM_CTRL_VALUE_I_VOLT_RMS_KI_C_NORMAL, \
        .iVoltRmsKiCFast = RTM_CTRL_VALUE_I_VOLT_RMS_KI_C_FAST, \
        .iVoltSyncLpf_Q12 = RTM_CTRL_VALUE_I_VOLT_SYNC_LPF_Q12, \
        .iVoltSyncRamp_Q12 = RTM_CTRL_VALUE_I_VOLT_SYNC_RAMP_Q12, \
        .iVoltRmsRamp_Q12 = RTM_CTRL_VALUE_I_VOLT_RMS_RAMP_Q12, \
        .uiVbusMidHoldCnt = RTM_CTRL_VALUE_UI_VBUS_MID_HOLD_CNT, \
        .uiVbusMidAdjustCnt = RTM_CTRL_VALUE_UI_VBUS_MID_ADJUST_CNT, \
        .iVbusMidThreshold = RTM_CTRL_VALUE_I_VBUS_MID_THRESHOLD, \
    }

#endif
