export type DebugErrorCode =
  | "SessionNotFound"
  | "CoreNotFound"
  | "DuplicateCoreId"
  | "DuplicateCoreTarget"
  | "DuplicateBoardId"
  | "DuplicateProbeAllocation"
  | "ProbeNotConnected"
  | "ProbeBindingMissing"
  | "ProbeBindingInvalid"
  | "CoreIdentityMissing"
  | "CoreIdentityMismatch"
  | "CoreNotConnected"
  | "OwnerCoreNotConnected"
  | "ProgramFileNotFound"
  | "ProgramLoadFailed"
  | "ProgramLoadSessionRefreshFailed"
  | "BatchOperationFailed"
  | "ArtifactPairInvalid"
  | "LaunchArtifactsMissing"
  | "StartupContractInvalid"
  | "LaunchProgramMissing"
  | "MemoryReadFailed"
  | "RamOwnershipVerifyFailed"
  | "TargetConnectFailed"
  | "TargetRunFailed"
  | "TargetHaltFailed"
  | "SymbolNotFound"
  | "ExpressionEvaluateFailed"
  | "ExpressionAssignFailed"
  | "ExpressionVerifyFailed"
  | "AddressResolveFailed"
  | "AdapterNotAvailable"
  | "DssNotFound"
  | "UnsafeDssLaunchPath"
  | "DssLaunchFailed"
  | "DssCommandFailed"
  | "DssTimeout"
  | "DssTransportFailed"
  | "DaemonUnavailable"
  | "DaemonRequestTimeout"
  | "DaemonEntrypointNotFound"
  | "DaemonStarting"
  | "DaemonAuthenticationFailed"
  | "DaemonProtocolError"
  | "DaemonInstanceInvalid"
  | "ToolNotFound"
  | "WorkerHeartbeatTimeout"
  | "WorkerCommandTimeout"
  | "WorkerUnavailable"
  | "WorkerEntrypointNotFound"
  | "WorkerIdentityMismatch"
  | "WorkerRestartLimitReached"
  | "DssUnresponsive"
  | "BoardQuarantined"
  | "BoardLeased"
  | "InsufficientBoardConcurrency"
  | "LeaseExpired"
  | "LeaseFencingRejected"
  | "LeaseOwnerMismatch"
  | "LeaseBoardMismatch"
  | "LeaseWorkerMismatch"
  | "LeaseRenewalFailed"
  | "LeaseInvalidated"
  | "PcanLibraryNotFound"
  | "PcanInitializeFailed"
  | "PcanWriteFailed"
  | "PcanReadFailed"
  | "PcanBusOff"
  | "PcanChannelInUse"
  | "PcanPlatformUnsupported"
  | "FlashLoadPreparationUnsupported"
  | "DestructiveFlashReloadBlocked"
  | "Cpu2BootReleaseSequenceInvalid"
  | "UnsupportedResetType"
  | "PostLaunchActionFailed"
  | "PostLaunchCheckFailed"
  | "CanProfileInvalid"
  | "CanAdapterUnavailable"
  | "CanBarrierTimeout"
  | "CanFrameMismatch"
  | "CanBusFaultInjected"
  | "CanDebugObservationFailed"
  | "BoardLeaseRequired"
  | "BoardGroupBusy"
  | "BoardGroupInvalidTransition"
  | "BoardGroupBarrierInvalid"
  | "BoardGroupBarrierTimeout"
  | "BoardGroupBarrierFailed"
  | "CanSafetyGateFailed"
  | "CanIndependentBusVerificationRequired"
  | "CanCrossBoardComparisonFailed"
  | "CanTestHookUnsupported"
  | "RamOwnershipEvidenceRequired"
  | "RamOwnershipMapUnavailable"
  | "RamOwnershipMapParseFailed"
  | "PathOutsideAllowedReadRoots"
  | "PathOutsideAllowedWriteRoots"
  | "PathResolutionFailed"
  | "ProbeNotFound"
  | "ProbeSelectionRequired"
  | "ProbeIdentityMismatch"
  | "ProbeRecoveryBlocked"
  | "DuplicateProbeId"
  | "ProbeQueueTimeout"
  | "SessionClosing"
  | "SessionClosed"
  | "SessionIdleTimeout"
  | "PersistentChannelDisconnected"
  | "PersistentChannelReconnectFailed"
  | "DssCommandTimeout"
  | "DssCommandRejected"
  | "DssSchedulerConflict"
  | "BatchExpressionFailed"
  | "ExpressionCaptureFailed"
  | "EvidenceCaptureFailed"
  | "EvidenceLimitExceeded"
  | "EvidenceSerializationFailed"
  | "SafetyGuardViolation"
  | "ExpressionWaitTimeout"
  | "TargetResetNotObserved"
  | "TargetResetBaselineInvalid"
  | "ResetEvidenceReadFailed"
  | "ResetCauseReadFailed"
  | "ArtifactHashMismatch"
  | "RestoreProgramsFailed"
  | "LoadVerificationFailed"
  | "ProgramUnchanged"
  | "WorkflowCleanupFailed"
  | "SessionBoardMismatch"
  | "SessionInvalidated"
  | "SessionIdentityMismatch"
  | "SessionAlreadyOpen"
  | "ResetCoreScopeInvalid"
  | "WorkerGenerationChanged"
  | "LeaseGenerationChanged"
  | "VariableStreamAlreadyActive"
  | "VariableStreamNotFound"
  | "VariableStreamIdentityMismatch"
  | "VariableTypeRequired"
  | "VariableTypeUnsupported"
  | "VariableEnumSignednessRequired"
  | "VariableWidthMismatch"
  | "VariableSymbolResolutionFailed"
  | "VariableAddressMissing"
  | "VariableAddressInvalid"
  | "VariableIntegerInvalid"
  | "VariableIntegerUnsafe"
  | "VariableArtifactSizeLimit"
  | "MockVariableReadError"
  | "MockVariableSequenceEmpty"
  | "UnsupportedLayout"
  | "DlogElementWidthMismatch"
  | "DlogBufferTooLarge"
  | "DlogIndexOutOfRange"
  | "DlogArtifactSizeLimit"
  | "DlogSymbolReadFailed"
  | "DlogAddressInvalid"
  | "DlogIntegerInvalid"
  | "DlogIntegerUnsafe"
  | "DlogNumberInvalid"
  | "DlogFloatInvalid"
  | "DlogValueOutOfRange"
  | "DlogStateInvalid"
  | "DlogSnapshotInconsistent"
  | "EradDeviceUnsupported"
  | "EradOwnershipConflict"
  | "EradResourcesUnavailable"
  | "EradResourceConflict"
  | "EradOverwriteSelectionRequired"
  | "EradAddressRangeInvalid"
  | "EradAddressInvalid"
  | "EradSymbolsRequired"
  | "EradSymbolNotFound"
  | "EradResourcesRequired"
  | "EradAddressesRequired"
  | "EradProfileNotConfigured"
  | "EradProfileAlreadyActive"
  | "EradProfileNotFound"
  | "EradProfileIdentityMismatch"
  | "EradProfileStateInvalid"
  | "EradProfileStillActive"
  | "EradCounterInvalid"
  | "EradSysclkInvalid"
  | "BaselineSchemaUnsupported"
  | "BaselineIdentityMismatch"
  | "CapabilityRequired"
  | "CapabilityExpired"
  | "CapabilityNotAllowedBySafetyProfile"
  | "CapabilityUnknown"
  | "CapabilityInvalidTtl"
  | "CapabilityReasonRequired"
  | "CapabilitySessionNotFound"
  | "ImprovementAnalyticsUnavailable"
  | "ProposalNotFound"
  | "ProposalReviewReasonRequired"
  | "ProposalNotReadyForReview"
  | "ProposalInvalidState"
  | "ProposalNotApproved"
  | "ImplementationPromptNotAllowed"
  | "ImprovementImplementationUnavailable"
  | "ImplementationNotAllowed"
  | "ImplementationBusy"
  | "CodingAgentUnavailable"
  | "CodingAgentFailed"
  | "CodingAgentTimeout"
  | "ProposalAssumptionInvalid"
  | "ImplementationAlreadyActive"
  | "ImprovementRunNotFound"
  | "ImplementationInvalidState"
  | "WorktreeInitializationFailed"
  | "WorktreeCleanupFailed"
  | "WorkspaceBoundaryViolation"
  | "ScopeViolation"
  | "UnexpectedBinaryChange"
  | "DependencyChangeNotAllowed"
  | "ValidationConfigurationUnavailable"
  | "ValidationFailed"
  | "ValidationTimeout"
  | "AgentCommittedChanges"
  | "NoCandidateChanges"
  | "CandidateCommitFailed"
  | "CandidateNotReady"
  | "CandidateDirtyAfterValidation"
  | "CandidateHeadChanged"
  | "CandidateHistoryUnexpected"
  | "CandidateRevalidationRequired"
  | "CandidatePublishFailed"
  | "RemoteRepositoryMismatch"
  | "RemoteBranchMismatch"
  | "GitHubCredentialsUnavailable"
  | "GitHubApiUnavailable"
  | "GitHubRateLimited"
  | "PullRequestNotFound"
  | "PullRequestInvalidState"
  | "ReviewEvidenceInvalid"
  | "ReviewFeedbackUnavailable"
  | "ReviewFeedbackNotFound"
  | "ReviewFeedbackMalformed"
  | "RevisionEvidenceChanged"
  | "RevisionNotAllowedAfterMerge"
  | "PullRequestClosed"
  | "RevisionProposalNotFound"
  | "RevisionProposalInvalidState"
  | "RevisionApprovalRequired"
  | "RevisionScopeViolation"
  | "RevisionRemoteDrift"
  | "RemoteBranchAdvanced"
  | "AutomatedRevisionLimitReached"
  | "NewImprovementProposalRecommended"
  | "HardwareEvidenceInvalid"
  | "CleanupNotAllowed"
  | "ImprovementDaemonRestarted"
  | "BaselineDrift"
  | "BaselineUnavailable"
  | "BaselineInvalid";

export interface StructuredError {
  code: DebugErrorCode | string;
  message: string;
  details?: Record<string, unknown>;
}

export class DebugMcpError extends Error {
  readonly code: DebugErrorCode;
  readonly details: Record<string, unknown>;

  constructor(code: DebugErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(message);
    this.name = code;
    this.code = code;
    this.details = details;
  }
}

export class StructuredToolError extends Error {
  readonly code: string;
  readonly details?: Record<string, unknown>;

  constructor(error: StructuredError) {
    super(error.message);
    this.name = error.code;
    this.code = error.code;
    this.details = error.details;
  }
}

export function toStructuredError(error: unknown): StructuredError {
  if (error instanceof DebugMcpError) {
    return { code: error.code, message: error.message, details: error.details };
  }
  if (error instanceof StructuredToolError) {
    return { code: error.code, message: error.message, ...(error.details ? { details: error.details } : {}) };
  }
  if (error instanceof Error) {
    return { code: "UnknownError", message: error.message };
  }
  return { code: "UnknownError", message: String(error) };
}
