export type DebugErrorCode =
  | "SessionNotFound"
  | "CoreNotFound"
  | "DuplicateCoreId"
  | "DuplicateCoreTarget"
  | "DuplicateBoardId"
  | "DuplicateProbeAllocation"
  | "ProbeNotConnected"
  | "ProbeBindingMissing"
  | "ProbeBindingInvalid"
  | "CoreIdentityMissing"
  | "CoreIdentityMismatch"
  | "CoreNotConnected"
  | "OwnerCoreNotConnected"
  | "ProgramFileNotFound"
  | "ProgramLoadFailed"
  | "BatchOperationFailed"
  | "ArtifactPairInvalid"
  | "LaunchProgramMissing"
  | "MemoryReadFailed"
  | "RamOwnershipVerifyFailed"
  | "TargetConnectFailed"
  | "TargetRunFailed"
  | "TargetHaltFailed"
  | "SymbolNotFound"
  | "ExpressionEvaluateFailed"
  | "ExpressionAssignFailed"
  | "ExpressionVerifyFailed"
  | "AddressResolveFailed"
  | "AdapterNotAvailable"
  | "DssNotFound"
  | "UnsafeDssLaunchPath"
  | "DssLaunchFailed"
  | "DssCommandFailed"
  | "DssTimeout"
  | "DssTransportFailed"
  | "DaemonUnavailable"
  | "DaemonRequestTimeout"
  | "DaemonEntrypointNotFound"
  | "DaemonStarting"
  | "DaemonAuthenticationFailed"
  | "DaemonProtocolError"
  | "DaemonInstanceInvalid"
  | "ToolNotFound"
  | "WorkerHeartbeatTimeout"
  | "WorkerCommandTimeout"
  | "WorkerUnavailable"
  | "WorkerEntrypointNotFound"
  | "WorkerIdentityMismatch"
  | "WorkerRestartLimitReached"
  | "DssUnresponsive"
  | "BoardQuarantined"
  | "BoardLeased"
  | "InsufficientBoardConcurrency"
  | "LeaseExpired"
  | "LeaseFencingRejected"
  | "LeaseOwnerMismatch"
  | "LeaseBoardMismatch"
  | "LeaseWorkerMismatch"
  | "LeaseRenewalFailed"
  | "LeaseInvalidated"
  | "PcanLibraryNotFound"
  | "PcanInitializeFailed"
  | "PcanWriteFailed"
  | "PcanReadFailed"
  | "PcanBusOff"
  | "PcanChannelInUse"
  | "PcanPlatformUnsupported"
  | "FlashLoadPreparationUnsupported"
  | "UnsupportedResetType"
  | "PostLaunchActionFailed"
  | "PostLaunchCheckFailed"
  | "CanProfileInvalid"
  | "CanAdapterUnavailable"
  | "CanBarrierTimeout"
  | "CanFrameMismatch"
  | "CanBusFaultInjected"
  | "CanDebugObservationFailed"
  | "BoardLeaseRequired"
  | "BoardGroupBusy"
  | "BoardGroupInvalidTransition"
  | "BoardGroupBarrierInvalid"
  | "BoardGroupBarrierTimeout"
  | "BoardGroupBarrierFailed"
  | "CanSafetyGateFailed"
  | "CanIndependentBusVerificationRequired"
  | "CanCrossBoardComparisonFailed"
  | "CanTestHookUnsupported"
  | "RamOwnershipEvidenceRequired"
  | "RamOwnershipMapUnavailable"
  | "RamOwnershipMapParseFailed"
  | "PathOutsideAllowedReadRoots"
  | "PathOutsideAllowedWriteRoots"
  | "PathResolutionFailed"
  | "ProbeNotFound"
  | "ProbeSelectionRequired"
  | "ProbeIdentityMismatch"
  | "ProbeRecoveryBlocked"
  | "DuplicateProbeId"
  | "ProbeQueueTimeout"
  | "SessionClosing"
  | "SessionClosed"
  | "SessionIdleTimeout"
  | "PersistentChannelDisconnected"
  | "PersistentChannelReconnectFailed"
  | "DssCommandTimeout"
  | "DssCommandRejected"
  | "DssSchedulerConflict"
  | "BatchExpressionFailed"
  | "EvidenceCaptureFailed"
  | "EvidenceLimitExceeded"
  | "EvidenceSerializationFailed"
  | "SafetyGuardViolation"
  | "ExpressionWaitTimeout"
  | "TargetResetNotObserved"
  | "ArtifactHashMismatch"
  | "RestoreProgramsFailed"
  | "LoadVerificationFailed"
  | "ProgramUnchanged"
  | "WorkflowCleanupFailed"
  | "SessionBoardMismatch"
  | "SessionInvalidated"
  | "SessionIdentityMismatch"
  | "WorkerGenerationChanged"
  | "LeaseGenerationChanged"
  | "VariableStreamAlreadyActive"
  | "VariableStreamNotFound"
  | "VariableStreamIdentityMismatch"
  | "VariableTypeRequired"
  | "VariableTypeUnsupported"
  | "VariableEnumSignednessRequired"
  | "VariableWidthMismatch"
  | "VariableSymbolResolutionFailed"
  | "VariableAddressMissing"
  | "VariableAddressInvalid"
  | "VariableIntegerInvalid"
  | "VariableIntegerUnsafe"
  | "VariableArtifactSizeLimit"
  | "MockVariableReadError"
  | "MockVariableSequenceEmpty"
  | "UnsupportedLayout"
  | "DlogElementWidthMismatch"
  | "DlogBufferTooLarge"
  | "DlogIndexOutOfRange"
  | "DlogArtifactSizeLimit"
  | "DlogSymbolReadFailed"
  | "DlogAddressInvalid"
  | "DlogIntegerInvalid"
  | "DlogIntegerUnsafe"
  | "DlogNumberInvalid"
  | "DlogFloatInvalid"
  | "DlogValueOutOfRange"
  | "DlogStateInvalid"
  | "DlogSnapshotInconsistent"
  | "EradDeviceUnsupported"
  | "EradOwnershipConflict"
  | "EradResourcesUnavailable"
  | "EradResourceConflict"
  | "EradOverwriteSelectionRequired"
  | "EradAddressRangeInvalid"
  | "EradAddressInvalid"
  | "EradSymbolsRequired"
  | "EradSymbolNotFound"
  | "EradResourcesRequired"
  | "EradAddressesRequired"
  | "EradProfileNotConfigured"
  | "EradProfileAlreadyActive"
  | "EradProfileNotFound"
  | "EradProfileIdentityMismatch"
  | "EradProfileStateInvalid"
  | "EradProfileStillActive"
  | "EradCounterInvalid"
  | "EradSysclkInvalid"
  | "BaselineSchemaUnsupported"
  | "BaselineIdentityMismatch";

export interface StructuredError {
  code: DebugErrorCode | string;
  message: string;
  details?: Record<string, unknown>;
}

export class DebugMcpError extends Error {
  readonly code: DebugErrorCode;
  readonly details: Record<string, unknown>;

  constructor(code: DebugErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(message);
    this.name = code;
    this.code = code;
    this.details = details;
  }
}

export function toStructuredError(error: unknown): StructuredError {
  if (error instanceof DebugMcpError) {
    return { code: error.code, message: error.message, details: error.details };
  }
  if (error instanceof Error) {
    return { code: "UnknownError", message: error.message };
  }
  return { code: "UnknownError", message: String(error) };
}
